version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: veloz
      POSTGRES_PASSWORD: veloz
      POSTGRES_DB: pedidos
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pedidos:
    image: palitodf/pedidos:1.0.0
    container_name: pedidos
    depends_on:
      - postgres
    ports:
      - "3001:3000"

  estoque:
    image: palitodf/estoque:1.0.0
    container_name: estoque
    ports:
      - "3002:3000"

  pagamentos:
    image: palitodf/pagamentos:1.0.0
    container_name: pagamentos
    ports:
      - "3003:3000"

  gateway:
    image: palitodf/gateway:1.0.0
    container_name: gateway
    depends_on:
      - pedidos
      - estoque
      - pagamentos
    ports:
      - "3000:3000"

volumes:
  pgdata:
